export const employeeSampleData = [{
    "id": 1,
    "name": 'lewis',
    "username": "rlewis0",
    "email": "rlewis0@icq.com",
    "password": "rr2lld",
    "role": "Driver",
    "contact_Number": 93386887,
    "nok_Name": "Raf Lewis",
    "nok_Number": 82885081,
    "address": "19 Dixon Place",
    "postalCode": 537352,
    "dischargeDate": null,
    "createdAt": "11/6/2021"
},
{
    "id": 2,
    "name": 'Daniel',
    "username": "gmcgahern1",
    "email": "gmcgahern1@issuu.com",
    "password": "EXtKlvAH",
    "role": "Staff",
    "contact_Number": 90687570,
    "nok_Name": "Gretchen McGahern",
    "nok_Number": 90550083,
    "address": "82320 Emmet Place",
    "postalCode": 537708,
    "dischargeDate": null,
    "createdAt": "6/5/2021"
},
{
    "id": 3,
    "name": 'John',
    "username": "dmassen2",
    "email": "dmassen2@gov.uk",
    "password": "ZJPzVho",
    "role": "Driver",
    "contact_Number": 88710891,
    "nok_Name": "Darb Massen",
    "nok_Number": 84484831,
    "address": "846 4th Way",
    "postalCode": 553949,
    "dischargeDate": null,
    "createdAt": "9/10/2021"
},
{
    "id": 4,
    "name": 'Paul',
    "username": "ghopkins3",
    "email": "ghopkins3@opera.com",
    "password": "XdZy15A",
    "role": "Driver",
    "contact_Number": 95774209,
    "nok_Name": "Gibbie Hopkins",
    "nok_Number": 80250829,
    "address": "10 Hermina Point",
    "postalCode": 596366,
    "dischargeDate": null,
    "createdAt": "6/29/2021"
},
{
    "id": 5,
    "name": 'Mabel',
    "username": "acanadas4",
    "email": "acanadas4@apple.com",
    "password": "vCZBKj0",
    "role": "Admin",
    "contact_Number": 92003022,
    "nok_Name": "Ardenia Canadas",
    "nok_Number": 99099953,
    "address": "12323 Dayton Street",
    "postalCode": 563194,
    "dischargeDate": null,
    "createdAt": "12/28/2021"
},
{
    "id": 6,
    "username": "mferrers5",
    "name": 'Carolyn',
    "email": "mferrers5@imageshack.us",
    "password": "szmYrkmxw",
    "role": "Staff",
    "contact_Number": 80162768,
    "nok_Name": "Mildred Ferrers",
    "nok_Number": 97579432,
    "address": "19396 Elka Crossing",
    "postalCode": 504965,
    "dischargeDate": null,
    "createdAt": "5/3/2021"
},
{
    "id": 7,
    "username": "cschimaschke6",
    "name": 'Bobby',
    "email": "cschimaschke6@xinhuanet.com",
    "password": "R1BS6TrnpG",
    "role": "Staff",
    "contact_Number": 82982641,
    "nok_Name": "Carolyne Schimaschke",
    "nok_Number": 99679314,
    "address": "85674 Golf View Junction",
    "postalCode": 575901,
    "dischargeDate": null,
    "createdAt": "2/13/2021"
},
{
    "id": 8,
    "name": 'Nat',
    "username": "gcicetti7",
    "email": "gcicetti7@ihg.com",
    "password": "yJKaIEDC2",
    "role": "Staff",
    "contact_Number": 97201141,
    "nok_Name": "Guilbert Cicetti",
    "nok_Number": 90533092,
    "address": "26731 Twin Pines Road",
    "postalCode": 595175,
    "dischargeDate": null,
    "createdAt": "6/30/2021"
},
{
    "id": 9,
    "name": 'Lim Ah Ming',
    "username": "mcandlish8",
    "email": "mcandlish8@live.com",
    "password": "wKYqMy7a3",
    "role": "Admin",
    "contact_Number": 85675555,
    "nok_Name": "Madelon Candlish",
    "nok_Number": 90616733,
    "address": "6 Reinke Pass",
    "postalCode": 592435,
    "dischargeDate": null,
    "createdAt": "9/6/2021"
},
{
    "id": 10,
    "name": 'Johnson Hua',
    "username": "bberesford9",
    "email": "bberesford9@nih.gov",
    "password": "pRlazDENdiY",
    "role": "Admin",
    "contact_Number": 98232720,
    "nok_Name": "Blanche Beresford",
    "nok_Number": 95247211,
    "address": "65 3rd Alley",
    "postalCode": 565208,
    "dischargeDate": null,
    "createdAt": "3/26/2021"
}]
